// Shared constants for the application

export const STUDY_FIELDS = [
  "Computer Science",
  "Mathematics",
  "Physics",
  "Biology",
  "Chemistry",
  "Engineering",
  "Literature",
  "Arts",
  "Autre"
] as const;

export type StudyField = typeof STUDY_FIELDS[number];

export const MOROCCAN_CITIES = [
  "Rabat",
  "Casablanca",
  "Marrakech",
  "Fès",
  "Tanger",
  "Agadir",
  "Meknès",
  "Oujda",
  "Kenitra",
  "Tétouan",
  "Safi",
  "Temara",
  "El Jadida",
  "Béni Mellal",
  "Nador",
  "Khouribga",
  "Settat",
  "Mohammedia",
  "Ksar El Kebir",
  "Larache"
] as const;

export type MoroccanCity = typeof MOROCCAN_CITIES[number];

// Stripe Connect supported countries with their codes
export const STRIPE_COUNTRIES = [
  { code: 'US', name: 'United States' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'CA', name: 'Canada' },
  { code: 'AU', name: 'Australia' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'AT', name: 'Austria' },
  { code: 'BE', name: 'Belgium' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'HR', name: 'Croatia' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'CZ', name: 'Czech Republic' },
  { code: 'DK', name: 'Denmark' },
  { code: 'EE', name: 'Estonia' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'France' },
  { code: 'DE', name: 'Germany' },
  { code: 'GR', name: 'Greece' },
  { code: 'HU', name: 'Hungary' },
  { code: 'IE', name: 'Ireland' },
  { code: 'IT', name: 'Italy' },
  { code: 'LV', name: 'Latvia' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MT', name: 'Malta' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'NO', name: 'Norway' },
  { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'RO', name: 'Romania' },
  { code: 'SK', name: 'Slovakia' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'ES', name: 'Spain' },
  { code: 'SE', name: 'Sweden' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'BR', name: 'Brazil' },
  { code: 'MX', name: 'Mexico' },
  { code: 'SG', name: 'Singapore' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'JP', name: 'Japan' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'TH', name: 'Thailand' },
  { code: 'IN', name: 'India' },
] as const;

export type StripeCountryCode = typeof STRIPE_COUNTRIES[number]['code'];

// Phone country codes mapping
export const COUNTRY_PHONE_CODES: Record<string, { code: string; format: string; example: string }> = {
  'US': { code: '+1', format: '(XXX) XXX-XXXX', example: '(555) 123-4567' },
  'CA': { code: '+1', format: '(XXX) XXX-XXXX', example: '(555) 123-4567' },
  'GB': { code: '+44', format: 'XXXX XXXXXX', example: '7700 900123' },
  'AU': { code: '+61', format: 'XXX XXX XXX', example: '412 345 678' },
  'NZ': { code: '+64', format: 'XX XXX XXXX', example: '21 123 4567' },
  'AT': { code: '+43', format: 'XXX XXXXXXX', example: '664 1234567' },
  'BE': { code: '+32', format: 'XXX XX XX XX', example: '470 12 34 56' },
  'BG': { code: '+359', format: 'XXX XXX XXX', example: '87 123 4567' },
  'HR': { code: '+385', format: 'XX XXX XXXX', example: '91 234 5678' },
  'CY': { code: '+357', format: 'XX XXXXXX', example: '96 123456' },
  'CZ': { code: '+420', format: 'XXX XXX XXX', example: '601 123 456' },
  'DK': { code: '+45', format: 'XX XX XX XX', example: '32 12 34 56' },
  'EE': { code: '+372', format: 'XXXX XXXX', example: '5123 4567' },
  'FI': { code: '+358', format: 'XX XXX XXXX', example: '50 123 4567' },
  'FR': { code: '+33', format: 'X XX XX XX XX', example: '6 12 34 56 78' },
  'DE': { code: '+49', format: 'XXX XXXXXXXX', example: '151 12345678' },
  'GR': { code: '+30', format: 'XXX XXX XXXX', example: '691 234 5678' },
  'HU': { code: '+36', format: 'XX XXX XXXX', example: '20 123 4567' },
  'IE': { code: '+353', format: 'XX XXX XXXX', example: '85 123 4567' },
  'IT': { code: '+39', format: 'XXX XXX XXXX', example: '312 345 6789' },
  'LV': { code: '+371', format: 'XX XXX XXX', example: '21 234 567' },
  'LT': { code: '+370', format: 'XXX XXXXX', example: '612 34567' },
  'LU': { code: '+352', format: 'XXX XXX XXX', example: '621 123 456' },
  'MT': { code: '+356', format: 'XXXX XXXX', example: '9696 1234' },
  'NL': { code: '+31', format: 'X XX XX XX XX', example: '6 12 34 56 78' },
  'NO': { code: '+47', format: 'XXX XX XXX', example: '406 12 345' },
  'PL': { code: '+48', format: 'XXX XXX XXX', example: '501 123 456' },
  'PT': { code: '+351', format: 'XXX XXX XXX', example: '912 345 678' },
  'RO': { code: '+40', format: 'XXX XXX XXX', example: '712 345 678' },
  'SK': { code: '+421', format: 'XXX XXX XXX', example: '901 123 456' },
  'SI': { code: '+386', format: 'XX XXX XXX', example: '31 234 567' },
  'ES': { code: '+34', format: 'XXX XXX XXX', example: '612 345 678' },
  'SE': { code: '+46', format: 'XX XXX XX XX', example: '70 123 45 67' },
  'CH': { code: '+41', format: 'XX XXX XX XX', example: '78 123 45 67' },
  'AE': { code: '+971', format: 'XX XXX XXXX', example: '50 123 4567' },
  'BR': { code: '+55', format: '(XX) XXXXX-XXXX', example: '(11) 91234-5678' },
  'MX': { code: '+52', format: 'XX XXXX XXXX', example: '55 1234 5678' },
  'SG': { code: '+65', format: 'XXXX XXXX', example: '8123 4567' },
  'HK': { code: '+852', format: 'XXXX XXXX', example: '5123 4567' },
  'JP': { code: '+81', format: 'XX-XXXX-XXXX', example: '90-1234-5678' },
  'MY': { code: '+60', format: 'XX-XXX XXXX', example: '12-345 6789' },
  'TH': { code: '+66', format: 'XX XXX XXXX', example: '81 234 5678' },
  'IN': { code: '+91', format: 'XXXXX XXXXX', example: '98765 43210' },
};